#include <stdio.h>
#include <cs50.h>
#include <math.h>

void check_card(long ccn, int last_digit);
int getdigit(long ccn, int n);
int numlength(long ccn);

int main(void)
{

    /*Variable Declaration */
    long ccn;

    /*Ask for credit card number to the user until he/she gives a positive number */
    do
    {
        ccn = get_long("Number: ");
    }
    while (ccn <= 0);

    /*Initializating the variables and calculating the length of the card number */
    int counter = numlength(ccn);
    int odds = 0;
    int even_digit_total = 0;

    /*First finds the odd digits in the card number */
    /*Then doubles each digit */
    /*For each number generated by doubling each digit, finds the sum of digits of these new numbers */
    for (int i = 0; i <= counter - 1; i = i + 2)
    {
        odds += getdigit(ccn, i);
    }

    /*Calculates the sum of digits in the even numbered places */
    int evens = 0;
    for (int i = 1; i <= counter - 1; i = i + 2)
    {
        evens = getdigit(ccn, i);
        evens *= 2;
        int counter2 = numlength(evens);
        for (int k = 1; k <= counter2; k++)
        {
            even_digit_total += getdigit((long)evens, counter2 - k);
        }

    }

    /*Assiging the last digit of the number found from Luhn's algorithm to variable last_digit */
    int last_digit = getdigit((long)(even_digit_total + odds), 0);

    /*Sends last_digit of number generated by Luhn's algorithm and credit card for check */
    check_card(ccn, last_digit);
}

void check_card(long ccn, int last_digit)
{
    if (last_digit != 0)
    {
        printf("INVALID\n");
    }
    else if ((getdigit(ccn, numlength(ccn) - 1) == 3) & ((getdigit(ccn, numlength(ccn) - 2) == 4)
             || (getdigit(ccn, numlength(ccn) - 2) == 7)) & (numlength(ccn) == 15))
    {
        printf("AMEX\n");
    }
    else if ((getdigit(ccn, numlength(ccn) - 1) == 4) & ((numlength(ccn) == 13) || (numlength(ccn) == 16)))
    {
        printf("VISA\n");
    }
    else if ((getdigit(ccn, numlength(ccn) - 1) == 5) & ((getdigit(ccn, numlength(ccn) - 2) >= 1) & (getdigit(ccn,
             numlength(ccn) - 2) <= 5)) & (numlength(ccn) == 16))
    {
        printf("MASTERCARD\n");
    }
    else
    {
        printf("INVALID\n");
    }
}


/*Calculates the lenght of a long number for later use purposes */
int numlength(long ccn)
{
    int counter = 0;
    while (ccn != 0)
    {
        ccn /= 10;
        counter++;
    }
    return counter;
}


/*Returns the nth digit from the end of a long number */
int getdigit(long ccn, int n)
{
    long x = ccn / pow(10, n);

    x = x % 10;

    return (int)x;
}